
package com.allianz.pricingdetailsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PricingDetailsService", targetNamespace = "http://www.allianz.com/PricingDetailsService/", wsdlLocation = "file:/E:/Dhananjaya-realspeed/SOAP-Training_Allianz/new/JAX-WS_RI_PRICING_WS/WebContent/WEB-INF/PricingDetailsService.wsdl")
public class PricingDetailsService
    extends Service
{

    private final static URL PRICINGDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRICINGDETAILSSERVICE_EXCEPTION;
    private final static QName PRICINGDETAILSSERVICE_QNAME = new QName("http://www.allianz.com/PricingDetailsService/", "PricingDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/Dhananjaya-realspeed/SOAP-Training_Allianz/new/JAX-WS_RI_PRICING_WS/WebContent/WEB-INF/PricingDetailsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICINGDETAILSSERVICE_WSDL_LOCATION = url;
        PRICINGDETAILSSERVICE_EXCEPTION = e;
    }

    public PricingDetailsService() {
        super(__getWsdlLocation(), PRICINGDETAILSSERVICE_QNAME);
    }

    public PricingDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICINGDETAILSSERVICE_QNAME, features);
    }

    public PricingDetailsService(URL wsdlLocation) {
        super(wsdlLocation, PRICINGDETAILSSERVICE_QNAME);
    }

    public PricingDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICINGDETAILSSERVICE_QNAME, features);
    }

    public PricingDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricingDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PricingDetails
     */
    @WebEndpoint(name = "PricingDetailsServiceSOAPPort")
    public PricingDetails getPricingDetailsServiceSOAPPort() {
        return super.getPort(new QName("http://www.allianz.com/PricingDetailsService/", "PricingDetailsServiceSOAPPort"), PricingDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricingDetails
     */
    @WebEndpoint(name = "PricingDetailsServiceSOAPPort")
    public PricingDetails getPricingDetailsServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.allianz.com/PricingDetailsService/", "PricingDetailsServiceSOAPPort"), PricingDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICINGDETAILSSERVICE_EXCEPTION!= null) {
            throw PRICINGDETAILSSERVICE_EXCEPTION;
        }
        return PRICINGDETAILSSERVICE_WSDL_LOCATION;
    }

}
