<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:is="http://www.irctc.co.in/IrctcService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="IrctcService" targetNamespace="http://www.irctc.co.in/IrctcService/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.irctc.co.in/IrctcService/">
    	
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="NewOperationRequest">
    <wsdl:part element="is:NewOperation" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="NewOperationResponse">
    <wsdl:part element="is:NewOperationResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="IrctcService">
    <wsdl:operation name="NewOperation">
      <wsdl:input message="is:NewOperationRequest"/>
      <wsdl:output message="is:NewOperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IrctcServiceSOAP" type="is:IrctcService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="NewOperation">
      <soap:operation soapAction="http://www.irctc.co.in/IrctcService/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IrctcService">
    <wsdl:port binding="is:IrctcServiceSOAP" name="IrctcServiceSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
